version: "3.9"
services:
  web:
    container_name: sshnginx
    build: /tmp/dockerbuild
    ports:
      - "666:80"
      - "32:22"
      - "1443:443"
    volumes:
      - /tmp/html:/var/www/html/
    cpuset: "2"
    mem_limit: 50M